spring:
  datasource:
    username: root
    password: mysql123
    url: jdbc:mysql://192.168.42.62:3306/guli_oms
    driver-class-name: com.mysql.jdbc.Driver
  #    nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.42.62:8848
  application:
    name: oms-service
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 6000